[phases.setup]
nixPkgs = ["python3", "gcc", "python3Packages.pip", "python3Packages.setuptools"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --no-cache-dir --prefer-binary -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "cd /app && uvicorn main:app --host 0.0.0.0 --port $PORT"
